# Generated by Django 4.0.2 on 2022-02-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_descr',
            new_name='descr',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='name',
        ),
    ]
